---
name: Running

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: http://development.example

    steps:
      - name: Development
        run: echo ${{ vars.key }}

  stg:
    needs: dev
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: http://staging.example

    steps:
      - name: Staging
        run: echo ${{ vars.key }}
  
  prd:
    needs: stg
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: http://production.example

    steps:
      - name: Production
        run: echo ${{ vars.key }}
